### ISSUE TITLE
Error in GDCquery(project = CancerProject, data.category = "Gene expression",  :    unused arguments (file.type = "results", legacy = TRUE)

### ISSUE THREAD

**Issue by Pravithaks** [ibsquare/MoonlightR#22] opened 2023-07-04 10:29 UTC
I was running the below code :
listMoonlight <- NULL
for (i in 1:4){
    dataDual <- moonlight(cancerType = "BRCA", 
                      dataType = "Gene expression",
                      directory = "data",
                      nSample = 10,
                      nTF = 5,
                      DiffGenes = TRUE,
                      BPname = c("apoptosis","proliferation of cells"),
                      stage = i)
    listMoonlight <- c(listMoonlight, list(dataDual))
    save(dataDual, file = paste0("dataDual_stage",as.roman(i), ".Rdata"))
}
it throws an error :
Error in GDCquery(project = CancerProject, data.category = "Gene expression",  :    unused arguments (file.type = "results", legacy = TRUE)
Pease Help. Looking forward to hear from you.
@Pravithaks

**Comment by mona-n** [comment] 2023-07-07 16:43
Hi, thanks for using Moonlight and letting us know about the errors you get! We are working on solving this through the open PRs and hopefully it should be resolved soon

**Comment by mtiberti** [comment] 2023-08-07 07:35
hi, this looks like a duplicate of #21 so I'm closing it as complete

**Closed as completed by mtiberti** 2023-08-07 07:35 UTC
